added key fingerprint in .ssh documentation
UMass-RC/unity-docs pull request #31
Opened 2022-09-14 16:19 UTC by mckeags7

2022-09-14 16:21 UTC, hakasapl requested changes
Just the tickmarks change, otherwise looks good

2022-09-14 16:21 UTC, hakasapl commented on docs/connecting/ssh.md
> +ssh-ed25519 255 SHA256:jC7BF7h5/RJo5Svx1v+lufdf+I/ogu5dQV2sUe+y8ek
```suggestion
`ssh-ed25519 255 SHA256:jC7BF7h5/RJo5Svx1v+lufdf+I/ogu5dQV2sUe+y8ek`
```

Wrap these in tickmarks so they show up as a code block

2022-09-14 16:22 UTC, hakasapl commented
Github doesn't like me including "```" in the suggestions, but just wrap the whole fingerprint with three tick marks at the start and the end so it becomes a code block.

2022-09-16 19:06 UTC, simonleary-umass-edu requested changes
![image](https://user-images.githubusercontent.com/71396965/190712700-6331b448-3373-4a17-8cab-6a63b35f7350.png)

without a code block the text is mashed into one line.
Do we really need an example? It's just a notepad window surrounding a copy of the text we already provided. We could just reword it to tell them to copy it into notepad, rather than "append the contents"

2022-09-16 21:03 UTC, hakasapl requested changes

2022-09-16 21:03 UTC, hakasapl commented on docs/connecting/ssh.md
>      Your username should be your email with all at's `@` and dot's `.` replaced with underscores `_`. View your username [here](https://unity.rc.umass.edu/panel/account.php)
This is not strictly correct. Often times this is true, but we use EPPN (Edu-person principal name) to create usernames, and sometimes people will have emails that are not the same as their netids. (I know this isn't part of this PR but I just spotted it, so could you update that as well?)

```suggestion
    Your username is in the format `<organization username>_<organization>_edu`. View your username [here](https://unity.rc.umass.edu/panel/account.php)
```

2022-09-16 21:17 UTC, hakasapl approved these changes
Looks good to me, thanks!

2022-09-19 20:55 UTC, bryank-cs approved these changes

2022-09-21 14:46 UTC, simonleary-umass-edu approved these changes

2022-09-21 15:51 UTC, merged